-- CRIAR A TABELA DE EMPRESA

CREATE TABLE EMPRESA (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	RAZAOSOCIAL VARCHAR(150) NOT NULL,
	CNPJ VARCHAR(20) NOT NULL UNIQUE
);

-- INSERIR ALGUMAS EMPRESAS
INSERT INTO EMPRESA (ID, RAZAOSOCIAL,CNPJ) VALUES
	(NEWID(), 'EMPRESA A', '32.696.834/0001-70'),
	(NEWID(), 'EMPRESA B', '61.735.979/0001-30');

--EXIBINDO OS REGISTROS DE EMPRESA
SELECT * FROM EMPRESA;

-- CRIAR A TABELA DE FUNCIONÁRIOS
CREATE TABLE FUNCIONARIO (
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL UNIQUE,
	MATRICULA VARCHAR(15) NOT NULL,
	DATA_ADMISSAO DATE NOT NULL,
	EMPRESA_ID UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID)
);
